/**
 * Payload de demonstração — volumes e listas fictícias para pré-visualizar modelos de relatório
 * (PDF / Excel / Word) sem depender de importações PaperCut na base de dados.
 */
export function obterDadosRelatorioDemo() {
  const now = new Date();
  const ano = now.getFullYear();
  const mes = now.getMonth() + 1;

  return {
    periodo: { ano, mes },
    demo: true,
    totais: {
      folhas: 482_650,
      paginas: 318_400,
      copias: 124_800,
      jobs: 9_842,
      folhas_duplex: 215_400,
      folhas_gray: 248_900,
      folhas_cor_ou_nao_gray: 233_750,
    },
    estimativas: {
      caixas_a4: 193.06,
      toner_relativo: 118.42,
      gasto_papel_mzn: 72_397.5,
      gasto_toner_estimado_mzn: 592_100,
      custo_total_estimado_mzn: 664_497.5,
    },
    por_departamento: [
      { departamento: 'Sinistros', folhas: 98_400 },
      { departamento: 'Subscrições — Particulares', folhas: 86_200 },
      { departamento: 'Subscrições — Empresarial', folhas: 72_100 },
      { departamento: 'Financeiro', folhas: 54_800 },
      { departamento: 'TI / Operações', folhas: 48_200 },
      { departamento: 'RH & Administração', folhas: 38_950 },
      { departamento: 'Jurídico', folhas: 29_400 },
      { departamento: 'Comunicação', folhas: 22_600 },
      { departamento: 'Auditoria interna', folhas: 18_200 },
      { departamento: 'Compliance', folhas: 13_800 },
    ],
    por_provincia: [
      { provincia: 'Maputo', folhas: 168_200 },
      { provincia: 'Matola', folhas: 92_400 },
      { provincia: 'Gaza', folhas: 48_300 },
      { provincia: 'Inhambane', folhas: 41_800 },
      { provincia: 'Sofala', folhas: 38_950 },
      { provincia: 'Manica', folhas: 32_100 },
      { provincia: 'Tete', folhas: 28_700 },
      { provincia: 'Zambézia', folhas: 24_600 },
      { provincia: 'Nampula', folhas: 21_400 },
      { provincia: 'Cabo Delgado', folhas: 18_200 },
      { provincia: 'Niassa', folhas: 12_800 },
    ],
    top_usuarios: [
      { usuario_papercut: 'm.santos', folhas: 42_800 },
      { usuario_papercut: 'a.machava', folhas: 38_200 },
      { usuario_papercut: 'j.cumbe', folhas: 35_950 },
      { usuario_papercut: 'l.tembe', folhas: 31_400 },
      { usuario_papercut: 'r.nhaca', folhas: 28_100 },
      { usuario_papercut: 's.muianga', folhas: 24_650 },
      { usuario_papercut: 'c.mabunda', folhas: 22_300 },
      { usuario_papercut: 'v.mandlate', folhas: 19_800 },
      { usuario_papercut: 'e.jorge', folhas: 17_200 },
      { usuario_papercut: 'p.cuamba', folhas: 14_500 },
      { usuario_papercut: 'd.matsinhe', folhas: 12_100 },
      { usuario_papercut: 'f.ualane', folhas: 10_400 },
    ],
    top_impressoras: [
      { impressora: 'KONICA MINOLTA bizhub C301i (Sede — Maputo)', folhas: 128_400 },
      { impressora: 'HP Color LaserJet Pro MFP 4303 (TI)', folhas: 96_200 },
      { impressora: 'RICOH IM C3000 (Sinistros)', folhas: 71_800 },
      { impressora: 'Canon imageRUNNER ADVANCE (Beira)', folhas: 58_300 },
      { impressora: 'Xerox VersaLink C405 (Nampula)', folhas: 44_100 },
      { impressora: 'HP LaserJet Enterprise M507 (Chimoio)', folhas: 36_950 },
      { impressora: 'Kyocera TASKalfa 3554ci (Quelimane)', folhas: 28_700 },
      { impressora: 'Brother MFC-L8900CDW (Tete)', folhas: 18_800 },
    ],
    consumiveis_aquisicao_no_mes: [
      {
        id: '00000000-0000-4000-8000-000000000001',
        provincia: 'Maputo',
        tipo: 'papel_a4',
        quantidade: 12,
        preco_unitario: 1850,
        preco_total: 22_200,
        data_aquisicao: `${ano}-${String(mes).padStart(2, '0')}-05`,
        data_termino: null,
        observacoes: 'Fornecedor demo — papel 80 g/m²',
        anexos: [
          {
            id: '00000000-0000-4000-8000-0000000000a1',
            nome_original: 'cotacao_papel_demo.pdf',
            documento_tipo: 'cotacao',
            mime_type: 'application/pdf',
            tamanho_bytes: 128_000,
          },
          {
            id: '00000000-0000-4000-8000-0000000000a2',
            nome_original: 'fatura_001_demo.pdf',
            documento_tipo: 'fatura',
            mime_type: 'application/pdf',
            tamanho_bytes: 96_000,
          },
        ],
      },
      {
        id: '00000000-0000-4000-8000-000000000002',
        provincia: 'Matola',
        tipo: 'toner',
        quantidade: 2,
        preco_unitario: 12_500,
        preco_total: 25_000,
        data_aquisicao: `${ano}-${String(mes).padStart(2, '0')}-18`,
        data_termino: null,
        observacoes: '',
        anexos: [
          {
            id: '00000000-0000-4000-8000-0000000000a3',
            nome_original: 'recibo_transferencia_demo.png',
            documento_tipo: 'comprovativo_pagamento',
            mime_type: 'image/png',
            tamanho_bytes: 42_000,
          },
        ],
      },
    ],
    resumo_consumiveis_mes: { num_registos: 2, total_mzn: 47_200 },
    resumo_utilizadores_mes: {
      num_utilizadores: 2,
      total_impressoes: 184,
      total_folhas: 12_450,
      custo_estimado_mzn: 8_920.5,
    },
    utilizadores: [
      {
        usuario: 'm.santos',
        departamento: 'Sinistros',
        provincia: 'Maputo',
        estatisticas: {
          total_impressoes: 98,
          total_paginas: 8_200,
          total_copias: 102,
          total_folhas: 9_840,
          impressoes_coloridas_folhas: 4_200,
          impressoes_grayscale_folhas: 5_640,
          impressoes_duplex_folhas: 3_100,
          caixas_a4_estimadas: 3.94,
          toner_estimado: 12.4,
          media_mensal_impressoes: 98,
          media_diaria_folhas: 317.4,
          custo_estimado_mzn: 6_240.2,
        },
        impressoes: [
          {
            usuario: 'm.santos',
            departamento: 'Sinistros',
            provincia: 'Maputo',
            data_hora: `${ano}-${String(mes).padStart(2, '0')}-08T09:15:00.000Z`,
            impressora: 'KONICA MINOLTA bizhub C301i',
            documento: 'Relatorio_sinistro_2024.pdf',
            paginas: 12,
            copias: 1,
            folhas: 12,
            papel: 'A4',
            duplex: true,
            grayscale: true,
            cliente: 'WS-SIN-042',
            idioma: 'pt',
            largura_mm: 210,
            altura_mm: 297,
          },
          {
            usuario: 'm.santos',
            departamento: 'Sinistros',
            provincia: 'Maputo',
            data_hora: `${ano}-${String(mes).padStart(2, '0')}-14T11:22:00.000Z`,
            impressora: 'KONICA MINOLTA bizhub C301i',
            documento: 'Fotos_avaria_color.jpg',
            paginas: 4,
            copias: 2,
            folhas: 8,
            papel: 'A4',
            duplex: false,
            grayscale: false,
            cliente: 'WS-SIN-042',
            idioma: '—',
            largura_mm: 210,
            altura_mm: 297,
          },
        ],
      },
      {
        usuario: 'a.machava',
        departamento: 'Financeiro',
        provincia: 'Maputo',
        estatisticas: {
          total_impressoes: 86,
          total_paginas: 2_100,
          total_copias: 90,
          total_folhas: 2_610,
          impressoes_coloridas_folhas: 400,
          impressoes_grayscale_folhas: 2_210,
          impressoes_duplex_folhas: 1_800,
          caixas_a4_estimadas: 1.04,
          toner_estimado: 3.2,
          media_mensal_impressoes: 86,
          media_diaria_folhas: 84.2,
          custo_estimado_mzn: 2_680.3,
        },
        impressoes: [
          {
            usuario: 'a.machava',
            departamento: 'Financeiro',
            provincia: 'Maputo',
            data_hora: `${ano}-${String(mes).padStart(2, '0')}-12T16:05:00.000Z`,
            impressora: 'HP Color LaserJet Pro MFP 4303',
            documento: 'Balancete_mensal.xlsx',
            paginas: 6,
            copias: 1,
            folhas: 6,
            papel: 'A4',
            duplex: true,
            grayscale: true,
            cliente: 'FIN-PC-18',
            idioma: 'pt',
            largura_mm: 210,
            altura_mm: 297,
          },
        ],
      },
    ],
  };
}
